<?php

require_once __DIR__ . '/../flight/util/UrlManager.php';
use flight\util\UrlManager;


/**
 * To use this test in phpStorm - remove "namespace" string from class under testing and "use" string in test file.
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-14 at 11:01:56.
 */
class UrlManagerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UrlManager
     */
    protected $object;

    /**
     * @var routes
     */
    protected $routes;

    /**
     * @var routes
     */
    protected $compareAbsoluteUrl;


    /**
     * Sets up the fixture.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $_SERVER['HTTP_HOST']     = 'hidemyass.dev';
        $_SERVER['SCRIPT_NAME']   = '/index.php';
        $_SERVER['DOCUMENT_ROOT'] = 'D:/server/hidemyass.dev';

        $this->compareAbsoluteUrl = "http://hidemyass.dev";

        $this->routes = array(
            '/'                                       => array('\controllers\Index', 'start'),
            '/proxy'                                  => array('\controllers\ProxyController', 'start'),
            '/session/@var:[a-z]*'                    => array('\controllers\Test', 'session'),
            '/@name/@id:[0-9]+'                       => array('\controllers\Test', 'test'),
            '/@name:[a-z]+/@action:[a-z]+/@id:[0-9]+' => array('\controllers\Test', 'testing'),
            '/@name/@action:[a-z]+'                   => array('\controllers\Test', 'create'),
        );
        $this->object = new UrlManager($this->routes);
    }

    /**
     * Tears down the fixture.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers flight\util\UrlManager::createUrl
     */
    public function testCreateUrl()
    {
        $absoluteUrl = $this->object->getAbsoluteUrl();

        $one   = $this->object->createUrl('index/start');
        $two   = $this->object->createUrl('test/test', array('name' => 'test', 'id' => 1));
        $three = $this->object->createUrl('test/testing', array('name' => 'test', 'action' => 'action', 'id' => 1));
        $four  = $this->object->createUrl('Proxy/start');
        $five  = $this->object->createUrl('Test/session', array('var' => 'var'));
        $six   = $this->object->createUrl('Test/create', array('name' => 'name', 'action' => 'action'));

        $this->assertEquals($absoluteUrl . '/', $one);
        $this->assertEquals($absoluteUrl . '/test/1', $two);
        $this->assertEquals($absoluteUrl . '/test/action/1', $three);
        $this->assertEquals($absoluteUrl . '/proxy', $four);
        $this->assertEquals($absoluteUrl . '/session/var', $five);
        $this->assertEquals($absoluteUrl . '/name/action', $six);
    }

    /**
     * @covers flight\util\UrlManager::getAbsoluteUrl
     */
    public function testGetAbsoluteUrl()
    {
        $this->assertEquals($this->object->getAbsoluteUrl(), $this->compareAbsoluteUrl);
    }
}
